# This file contains the [pre-commit](https://pre-commit.com/) configuration of this repository.
# More on which specific pre-commit hooks we use can be found in README.md.
---
# minimum_pre_commit_version: "2.9.2"
# repos:
#   - repo: meta
#     hooks:
#       - id: identity
#       - id: check-hooks-apply
#
repos:
  # Formats yaml, markdown, etc.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier

  # Keeps revs in poetry.lock in sync with the revs in this hook
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: "1.1.0" # the revision or tag to clone at
    hooks:
      - id: sync_with_poetry
        args: [] # optional args

  # Check package, write lockfil and export requirements.txt
  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]

  # Run linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      # - id: ruff
      #   types_or: [python, pyi, jupyter]
      #   args: [--fix]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
