repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]

  # - repo: https://github.com/psf/black
  #   rev: 23.10.0
  #   hooks:
  #     - id: black
  #       args: ["--line-length", "80"]

#  - repo: local
#    hooks:
#      - id: pylint
#        name: pylint
#        entry: pylint
#        language: system
#        types: [python]
#        require_serial: true

  # - repo: https://github.com/pytest-dev/pytest.git
  #   rev: 7.4.3
  #   hooks:
  #    - id: pytest

