site_name: chirpdetector

theme:
  name: material
  favicon: assets/logo.png
  logo: assets/logo.png
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy

  icon:
    repo: fontawesome/brands/github


plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
  - search
  - glightbox
  
extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_url: https://github.com/weygoldt/chirpdetector
repo_name: weygoldt/chirpdetector

nav:
    - 'Home': 
      - 'Introduction': 'index.md'  
      - 'How it works': 'how_it_works.md'
    - 'Demo': 'demo.md'
    - 'Getting started':
      - 'Installation': 'installation.md'
      - 'Setup': 'setup.md'
      - 'Detection': 'detection.md'
      - 'Assingment': 'assingment.md'
      - 'Visualization': 'visualization.md'
    - 'Custom training':
      - 'Creating a dataset': 'dataset.md'
      - 'Labeling a dataset': 'labeling.md'
      - 'Training': 'training.md'
      - 'Helper commands': 'yolo-helpers.md'
    - 'Contributing': 'contributing.md'
    - 'API Reference':
      - 'train_model': 'api/train_model.md'
      - 'detect_chirps': 'api/detect_chirps.md'
      - 'assign_chirps': 'api/assign_chirps.md'
      - 'plot_detections': 'api/plot_detections.md'
      - 'convert_data': 'api/convert_data.md'
      - 'dataset_utils': 'api/dataset_utils.md'
      

