site_name: chirpdetector

theme:
  name: material
  favicon: /assets/logo.svg
  logo: /assets/logo.svg
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy

  icon:
    repo: fontawesome/brands/github


plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
  - search
  
extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

repo_url: https://github.com/weygoldt/chirpdetector
repo_name: weygoldt/chirpdetector

nav:
    - Home: 'index.md'
    # - 'User guide':
    #     - 'Detection': '/detection.md'
    # - 'Example workflows':
    #     - 'Example 1': '/example1.md'
    # - 'Contributing': 'contributing.md'

