[hyperparameters]
width = 1076
height = 430
classes = ["__background__", "chirp"]
num_epochs = 5 
batch_size = 2 
kfolds = 5
learning_rate = 0.001 
momentum = 0.9
weight_decay = 0.0005
num_workers = 4
modelpath = "/home/weygoldt/Projects/mscthesis/data/processed/models" 

[training]
datapath = "/home/weygoldt/Projects/mscthesis/data/processed/deepnn/train"

[detection]
threshold = 0.5
time_window = 20 
freq_window = [100, 2200]
freq_res = 6
overlap_frac = 0.9
spec_overlap = 1
